#27 수정 및 유용한 함수 추가
suhdonghwi/nuri pull request #28
Opened 2020-10-19 11:15 UTC by CraftyDragon678

하스켈에 있는 foldr, take, (!!) 함수를 구현하고 `목록으로 보여주다` 함수를 수정하였습니다.

2020-10-19 23:47 UTC, suhdonghwi requested changes
좋은 예시 추가 감사합니다! 주석 부분만 수정해주시면 머지할게요 👍

2020-10-19 23:47 UTC, suhdonghwi commented on examples/유용한 함수들.nuri
> +# 목록을 받고 숫자를 받아 하나를 가져
이 부분 주석에 오타가 있는 것 같습니다!

2020-10-20 05:31 UTC, CraftyDragon678 commented on examples/유용한 함수들.nuri
> +# 목록을 받고 숫자를 받아 하나를 가져
해당부분 f9a430cde744965fb990912cab1e97251eed3507 에서 수정하였습니다!

2020-10-26 04:52 UTC, suhdonghwi approved these changes

2020-10-26 04:53 UTC, merged